/**
 * Actions types and other constants for incident types
 *
 * @version 0.1.0
 * @since 0.1.0
 */

// incident types
export const GET_INCIDENT_TYPES_START = 'GET_INCIDENT_TYPES_START';
export const GET_INCIDENT_TYPES_SUCCESS = 'GET_INCIDENT_TYPES_SUCCESS';
export const GET_INCIDENT_TYPES_ERROR = 'GET_INCIDENT_TYPES_ERROR';

// incident type
export const GET_INCIDENT_TYPE_START = 'GET_INCIDENT_TYPE_START';
export const GET_INCIDENT_TYPE_SUCCESS = 'GET_INCIDENT_TYPE_SUCCESS';
export const GET_INCIDENT_TYPE_ERROR = 'GET_INCIDENT_TYPE_ERROR';

export const POST_INCIDENT_TYPE_START = 'POST_INCIDENT_TYPE_START';
export const POST_INCIDENT_TYPE_SUCCESS = 'POST_INCIDENT_TYPE_SUCCESS';
export const POST_INCIDENT_TYPE_ERROR = 'POST_INCIDENT_TYPE_ERROR';

export const PUT_INCIDENT_TYPE_START = 'PUT_INCIDENT_TYPE_START';
export const PUT_INCIDENT_TYPE_SUCCESS = 'PUT_INCIDENT_TYPE_SUCCESS';
export const PUT_INCIDENT_TYPE_ERROR = 'PUT_INCIDENT_TYPE_ERROR';

export const DELETE_INCIDENT_TYPE_START = 'DELETE_INCIDENT_TYPE_START';
export const DELETE_INCIDENT_TYPE_SUCCESS = 'DELETE_INCIDENT_TYPE_SUCCESS';
export const DELETE_INCIDENT_TYPE_ERROR = 'DELETE_INCIDENT_TYPE_ERROR';

export const SELECT_INCIDENT_TYPE = 'SELECT_INCIDENT_TYPE';
